# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create centroid GeoJSON index

on:
  push:
    branches: [ main ]
    paths:
      - 'las-files/*.las'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  centroid-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup micromamba with PDAL
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: pdal-env
          create-args: >-
            -c conda-forge
            python
            pdal
            python-pdal
          cache-environment: true
          init-shell: bash

      - name: Check PDAL & Python bindings
        shell: bash -l {0}
        run: |
          set -eo pipefail
          micromamba run -n pdal-env pdal --version
          micromamba run -n pdal-env python - <<'PY'
          import pdal
          print("python-pdal OK")
          PY

      - name: Build index.geojson via Python
        shell: bash -l {0}
        run: |
          set -eo pipefail
          micromamba run -n pdal-env python script.py --glob 'las-files/*.las' --out index.geojson --pretty

      - name: Commit only index.geojson
        shell: bash -l {0}
        run: |
          set -eo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.geojson
          if ! git diff --cached --quiet; then
            git commit -m "Update centroid index [skip ci]"
            git push
          else
            echo "No changes in index.geojson."
          fi