name: Create GeoJSON of LAS center coordinates when merged PR

on:
  pull_request:
    types: [closed]

jobs:
  append-centers:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      OUT_GEOJSON: "centers/las_centers.geojson" #Path to output GeoJSON file

    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - name: Set up PDAL environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: pdal-env
          create-args: >
            python=3.11
            pdal
            pyproj
            jq
          init-shell: bash

      - name: Determine changed LAS files in this PR
        id: diffs
        shell: bash -l {0}
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" -- '*.las' '*.LAS' '*.laz' '*.LAZ' | tr '\n' ' ')
          echo "files=$CHANGED" >> $GITHUB_OUTPUT
          echo "Changed LAS/LAZ files: $CHANGED"

      - name: Append/Update features into a single GeoJSON
        if: steps.diffs.outputs.files != ''
        shell: bash -l {0}
        run: |
          mkdir -p "$(dirname "$OUT_GEOJSON")"
          micromamba run -n pdal-env python scripts/create_geojson --out "$OUT_GEOJSON" ${{ steps.diffs.outputs.files }}

      - name: Commit and push results
        if: steps.diffs.outputs.files != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Append/Update LAS centers into ${OUT_GEOJSON}"
          git push origin HEAD:main
