# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create centroid GeoJSON index

on:
  push:
    branches: [ main ]
    paths:
      - 'las-files/*.las'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  centroid-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup micromamba with PDAL
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: pdal-env
          create-args: >-
            -c conda-forge
            pdal
          cache-environment: true
          init-shell: bash

      - name: Build index.geojson via Python
        shell: bash -l {0}
        run: |
          micromamba activate pdal-env
          python3 script.py --glob 'las-files/*.las' --out index.geojson --pretty